### ISSUE TITLE
Show sexp diff in assert output

### ISSUE THREAD

**Issue by brendanlong** [janestreet/ppx_assert#3] opened 2019-06-12 16:57 UTC
We sometimes use ppx assert to compare fairly large sexps, and it's frustrating to try to figure out what's wrong when you get output like this:

```
(monitor.ml.Error
  (runtime-lib/runtime.ml.E "got unexpected result"
    ((expected
       ((Applications
          (((application_id 451205)
             (applicant
               ((applicant_id 72931) (first_name Minimal) (middle_name ())
                 (last_name Row) (email minimal@example.com)))
             (requisition
               ((requisition_id 18399)
                 (job
                   (((job_id 120) (label ("Fake description"))
                      (department ())
                      (facility
                        ((facility_id 6107) (label ("Another Facility"))))
                      (job_family ()))))
                 (label ("Community Sales Associate")) (status ())
                 (start_date ()) (end_date ()) (update_date ())
                 (subscribers ()) (job_description ()) (requirements ())
                 (education_level ())))
             (status ("Invited to Group Interview"))
             (application_date ((2019-05-21 20:00:00.000000-04:00)))
             (disposition_reason ()) (disposition_code ())
             (disposition_updated ()) (employee ())
             (application_questions ()) (push_back_id ()))
            ((application_id 451309)
              (applicant
                ((applicant_id 56915) (first_name John) (middle_name (Q))
                  (last_name Smith) (email john.smith@example.com)))
              (requisition
                ((requisition_id 17850)
                  (job
                    (((job_id 402) (label ("Fake description"))
                       (department
                         (((department_id b9150)
                            (label ("Sales and General & Admin")))))
                       (facility
                         ((facility_id 1544) (label ("Example Facility"))))
                       (job_family ()))))
                  (label ("Director of Example")) (status ()) (start_date ())
                  (end_date ()) (update_date ()) (subscribers ())
                  (job_description ()) (requirements ())
                  (education_level ())))
              (status ("New Candidate"))
              (application_date ((2019-05-21 20:00:00.000000-04:00)))
              (disposition_reason ()) (disposition_code ())
              (disposition_updated ()) (employee ())
              (application_questions ()) (push_back_id ()))))
         ()))
      (got
        ((Applications
           (((application_id 451205)
              (applicant
                ((applicant_id 72931) (first_name Minimal) (middle_name ())
                  (last_name Row) (email minimal@example.com)))
              (requisition
                ((requisition_id 18399)
                  (job
                    (((job_id 120) (label ("Fake description"))
                       (department ())
                       (facility
                         ((facility_id 6107) (label ("Another Facility"))))
                       (job_family ()))))
                  (label ("Community Sales Associate")) (status ())
                  (start_date ()) (end_date ()) (update_date ())
                  (subscribers ()) (job_description ()) (requirements ())
                  (education_level ())))
              (status ("Invited to Group Interview"))
              (application_date ((2019-05-21 20:00:00.000000-04:00)))
              (disposition_reason ()) (disposition_code ())
              (disposition_updated ()) (employee ())
              (application_questions ()) (push_back_id ()))
             ((application_id 451309)
               (applicant
                 ((applicant_id 56915) (first_name John) (middle_name (Q))
                   (last_name Smith) (email john.smith@example.com)))
               (requisition
                 ((requisition_id 17850)
                   (job
                     (((job_id 402) (label ("Fake description"))
                        (department
                          (((department_id a9150)
                             (label ("Sales and General & Admin")))))
                        (facility
                          ((facility_id 1544) (label ("Example Facility"))))
                        (job_family ()))))
                   (label ("Director of Example")) (status ())
                   (start_date ()) (end_date ()) (update_date ())
                   (subscribers ()) (job_description ()) (requirements ())
                   (education_level ())))
               (status ("New Candidate"))
               (application_date ((2019-05-21 20:00:00.000000-04:00)))
               (disposition_reason ()) (disposition_code ())
               (disposition_updated ()) (employee ())
               (application_questions ()) (push_back_id ()))))
          ()))
      (Loc nectar/test/test_nectar_load.ml:94:17)))
  ("Raised at file \"runtime-lib/runtime.ml\", line 28, characters 28-53"
    "Called from file \"src/deferred1.ml\", line 20, characters 40-45"
    "Called from file \"src/job_queue.ml\", line 159, characters 6-47"))
```

In this case, I manually added:

```
  let diff =
    let sexp_of = [%sexp_of: Load.t * Error.t list] in
    Core_extended.Extended_sexp.Diff.(
      of_sexps ~original:(sexp_of expect) ~updated:(sexp_of actual)
      |> Option.map ~f:to_string)
      |> Option.value ~default:"No difference"
  in
  [%test_result: Load.t * Error.t list] ~expect actual ~message:(sprintf "Values don't match. Difference is: %s" diff)
```

And then I get a better (although not ideally formatted) message at the top:

```
(monitor.ml.Error
  (runtime-lib/runtime.ml.E
     "Values don't match. Difference is:  (\
    \n  (\
    \n   (\
    \n    requisition\
    \n     job\
    \n      (\
    \n       department\
    \n        (\
    \n         department_id\
    \n-         b9150\
    \n+         a9150\
    \n        )\
    \n      )\
    \n   )\
    \n  )\
    \n )\
    \n: got unexpected result"
    (* original message goes here *)
```

Would it be possible to add this to the standard output?

**Comment by v-gb** [comment] 2020-05-26 18:06
Sorry for the lack of response, things should be more prompt going forward.

The problem is clear. What I'm wondering about is:

- do you still care about this?
- given your example, I'm assuming this is for tests, in which case have you considered [expect tests](https://github.com/janestreet/ppx_expect)? They may well be a better solution (it gives you colors in the diff, context, and automatic correction)

**Comment by v-gb** [comment] 2020-06-02 14:11
Given the age of the request, I'm going to assume this was worked around somehow, and close this. Reopen if you still want this (in which case I'd like to know the answer to the question above).

**Closed as completed by v-gb** 2020-06-02 14:11 UTC
Labels: forwarded-to-js-devs

**Comment by brendanlong** [comment] 2020-06-02 16:07
Sorry, I didn't see the other comment. I'll see if I can do what I want with expect tests.
